### PR TITLE
Upgrade grammar and settings

### PR DESCRIPTION
**Pull request by MadcapJake**
### Changes
- Add declarations
- Add core functions
- Add Atom-specific settings
- Transform to CSON for readability
- Add Char literal
- Add inheritance
- Add interpolation
### Example

example

### CODE REVIEW

**Comment by hackwaly** [comment]
Awesome work! Would you like to take over this project? I can transfer the github repo and apm package ownership to you.

**Comment by hackwaly** [comment]
image
When there's no blank line between two deftype (or defstruct). It doesn't highlight correctly.

**Comment by MadcapJake** [comment]
I'll check that out, I'd be glad to take this over too.

**Comment by hackwaly** [comment]
I'm trying to make a transfer. But I've got this message. 

> MadcapJake/language-stanza already exists

Maybe establishing a new organization named atom-stanza is a good idea.

**Comment by MadcapJake** [comment]
Sure, otherwise I could delete my fork :smile:

Edit: it's been deleted

**Comment by hackwaly** [comment]
I've made an repo transfer. I didn't know how to transfer apm package or give you apm package publish privilege.

**Comment by MadcapJake** [comment]
`apm unpublish language-stanza` and then I do `apm publish language-stanza`

**Comment by hackwaly** [comment]
@MadcapJake done.

**Comment by MadcapJake** [comment]
...and done! Thanks @hackwaly!

**Comment by hackwaly** [comment]
My pleasure!

**Pull request merged**
